### ISSUE TITLE
Cannot read property 'ordinal' of undefined at setupXAxis

### ISSUE THREAD

**Issue by Saganus** [gregjopa/d3-server-side-demo#1]
I know this is a very old project, but it's a very interesting one and would love to get it to run.

Right now I'm getting:

```
TypeError: /home/akram/external_projects/d3-server-side-demo/index.html:28
    26|   <body>
    27|     <h1>D3 Server-side Demo</h1>
 >> 28|     <%-
    29|       barChartHelper.getBarChart({
    30|         data: fixtureData,
    31|         width: 400,

Cannot read property 'ordinal' of undefined
    at setupXAxis (/home/akram/external_projects/d3-server-side-demo/bar_chart.js:61:24)
    at chart (/home/akram/external_projects/d3-server-side-demo/bar_chart.js:35:5)
    at Selection.selection_call [as call] (/home/akram/external_projects/d3-server-side-demo/node_modules/d3-selection/build/d3-selection.js:500:12)
    at Object.getBarChart (/home/akram/external_projects/d3-server-side-demo/bar_chart_helper.js:17:68)
    at eval (eval at compile (/home/akram/external_projects/d3-server-side-demo/node_modules/ejs/lib/ejs.js:481:12), <anonymous>:12:22)
    at returnedFn (/home/akram/external_projects/d3-server-side-demo/node_modules/ejs/lib/ejs.js:512:17)
    at View.exports.renderFile [as engine] (/home/akram/external_projects/d3-server-side-demo/node_modules/ejs/lib/ejs.js:364:31)
    at View.render (/home/akram/external_projects/d3-server-side-demo/node_modules/express/lib/view.js:126:8)
    at tryRender (/home/akram/external_projects/d3-server-side-demo/node_modules/express/lib/application.js:639:10)
    at Function.render (/home/akram/external_projects/d3-server-side-demo/node_modules/express/lib/application.js:591:3)
```

After some trial and error I found out that if I upgrade the d3 version in package.json to a recent one (^4.5.0) then things break.

I guess the methods changed from d3 3.5.6 to d3 4.5.0.

I will try to see if I can fix the error and submit a PR

**Comment by serganus** [comment]
+1

**Comment by diogobaltazar** [comment]
@Saganus  check the [PR](https://github.com/gregjopa/d3-server-side-demo/pull/3), it has it up and running

**Comment by gregjopa** [comment]
@Saganus this project has been updated to support d3 v5. You should no longer experience this error.
